name: bot

services:
  dev:
    container_name: bot
    build:
      context: .
      args:
        BASE_IMAGE: bot-isaac-base:3.2
    image: bot-ros:humble
    runtime: nvidia
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    working_dir: /workspace
    volumes:
      - ..:/workspace:ro
      - build:/workspace/ros/build
      - install:/workspace/ros/install
      - log:/workspace/ros/log
      - ../.cache/zed/resources:/usr/local/zed/resources
      - ../.cache/zed/settings:/usr/local/zed/settings
      - /dev:/dev
      - /tmp:/tmp
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    stdin_open: true
    tty: true

volumes:
  build:
  install:
  log:
